name: staging

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1 

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: Install
        run: yarn

      - name: Run fastlane
        working-directory: ios
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          MATCH_REPO: git@github.com:diego3g/deployrn-certs.git
          APPLE_ACCOUNT: diego.schell.f@gmail.com
          TEAM_ID: KKY728EKXK
        run: fastlane ci_testflight