name: staging

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1 

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Install NPM dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('ios/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install bundle dependencies
        working-directory: ios
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pod dependencies
        working-directory: ios
        run: pod install

      - name: Brew
        run: brew install librsvg imagemagick

      - name: Run fastlane
        working-directory: ios
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_REPO: git@github.com:diego3g/deployrn-certs.git
          APPLE_ACCOUNT: diego.schell.f@gmail.com
          TEAM_ID: KKY728EKXK
        run: fastlane ci_testflight